FROM node:20-alpine
WORKDIR /app

# Copia package*.json primero para cache de npm ci si quieres
# COPY package*.json /app/
# RUN npm ci

# Para dev montamos la carpeta, así que solo exponemos puerto
EXPOSE 5173
