services:
  db:
    image: postgres:16
    container_name: transporte_db
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-transporte}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      TZ: "America/La_Paz"
      PGTZ: "America/La_Paz"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-transporte}",
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transporte_backend
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_HOST: db
      REDIS_URL: "redis://redis:6379/0"
      # IP automática habilitada
      AUTO_DETECT_IP: "true"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: bash -lc "python detect_ip.py && python manage.py migrate --noinput || true && python manage.py seed user rol --force && python manage.py collectstatic --noinput || true && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transporte_frontend
    working_dir: /app
    env_file:
      - ./frontend/.env
    environment:
      HOST: "0.0.0.0"  # Vite necesita HOST para exponer en 0.0.0.0
      # Dejamos VITE_API_URL vacío para habilitar detección automática
      VITE_API_URL: ""
    volumes:
      - ./frontend:/app
    command: sh -lc "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: transporte_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    container_name: transporte_mailhog
    ports:
      - "1025:1025" # Puerto SMTP para que Django envíe correos
      - "8025:8025" # Interfaz web para ver los correos

volumes:
  pgdata:
  redis_data:
