# Generated by Django 5.0.7 on 2025-10-13 13:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0002_rename_ubicaciones_tipo_idx_ubicaciones_tipo_96ab23_idx_and_more'),
        ('vehiculos', '0002_alter_vehiculo_conductor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la solicitud')),
                ('fecha_viaje', models.DateField(help_text='Fecha planificada para el viaje')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio del viaje desde el depot')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado actual de la solicitud', max_length=20)),
                ('mensaje_resultado', models.TextField(blank=True, help_text='Mensaje de resultado o error de la optimización', null=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, help_text='Fecha y hora en que se procesó la solicitud', null=True)),
                ('depot', models.ForeignKey(blank=True, help_text='Ubicación de inicio y fin de las rutas (ej: terminal, almacén)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_depot', to='ubicaciones.ubicacion')),
                ('vehiculos_disponibles', models.ManyToManyField(help_text='Vehículos que pueden ser asignados a esta ruta', related_name='solicitudes_ruta', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Solicitud de Ruta',
                'verbose_name_plural': 'Solicitudes de Ruta',
                'db_table': 'solicitudes_ruta',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RutaOptimizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ruta', models.PositiveIntegerField(default=1, help_text='Número de ruta (1, 2, 3... si hay múltiples vehículos)')),
                ('distancia_total_km', models.DecimalField(decimal_places=2, default=0, help_text='Distancia total de la ruta en kilómetros', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tiempo_total_min', models.PositiveIntegerField(default=0, help_text='Tiempo total de la ruta en minutos (incluyendo servicio)')),
                ('carga_total_kg', models.DecimalField(decimal_places=2, default=0, help_text='Carga total transportada en kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Costo estimado de la ruta', max_digits=10, null=True)),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de la ruta desde el depot')),
                ('hora_fin_estimada', models.TimeField(blank=True, help_text='Hora estimada de regreso al depot', null=True)),
                ('completada', models.BooleanField(default=False, help_text='Indica si la ruta ha sido completada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.ForeignKey(help_text='Vehículo asignado a esta ruta', on_delete=django.db.models.deletion.PROTECT, related_name='rutas_optimizadas', to='vehiculos.vehiculo')),
                ('solicitud', models.ForeignKey(help_text='Solicitud de ruta que generó esta solución', on_delete=django.db.models.deletion.CASCADE, related_name='rutas_optimizadas', to='rutas_optimizadas.solicitudruta')),
            ],
            options={
                'verbose_name': 'Ruta Optimizada',
                'verbose_name_plural': 'Rutas Optimizadas',
                'db_table': 'rutas_optimizadas',
                'ordering': ['solicitud', 'numero_ruta'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pickup', 'Recogida'), ('delivery', 'Entrega'), ('both', 'Recogida y Entrega')], default='delivery', help_text='Tipo de operación: recogida, entrega o ambas', max_length=10)),
                ('ventana_tiempo_inicio', models.TimeField(blank=True, help_text='Hora más temprana para atender esta ubicación', null=True)),
                ('ventana_tiempo_fin', models.TimeField(blank=True, help_text='Hora más tardía para atender esta ubicación', null=True)),
                ('demanda_peso', models.DecimalField(decimal_places=2, default=0, help_text='Peso de la carga en kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('demanda_volumen', models.DecimalField(decimal_places=2, default=0, help_text='Volumen de la carga en m³', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tiempo_servicio_min', models.PositiveIntegerField(blank=True, help_text='Tiempo de servicio en minutos (si es diferente al de la ubicación)', null=True)),
                ('prioridad', models.PositiveIntegerField(default=1, help_text='Prioridad de la entrega (1=normal, mayor=más urgente)', validators=[django.core.validators.MinValueValidator(1)])),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la entrega', null=True)),
                ('ubicacion', models.ForeignKey(help_text='Ubicación donde se realiza la entrega/recogida', on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='ubicaciones.ubicacion')),
                ('solicitud', models.ForeignKey(help_text='Solicitud de ruta a la que pertenece esta entrega', on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='rutas_optimizadas.solicitudruta')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'entregas',
                'ordering': ['solicitud', 'prioridad'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(help_text='Orden de visita en la ruta (0=depot inicio, N+1=depot fin)')),
                ('tiempo_llegada_estimado', models.TimeField(blank=True, help_text='Hora estimada de llegada a esta parada', null=True)),
                ('tiempo_salida_estimado', models.TimeField(blank=True, help_text='Hora estimada de salida de esta parada', null=True)),
                ('tiempo_servicio_min', models.PositiveIntegerField(default=0, help_text='Tiempo de servicio en esta parada en minutos')),
                ('distancia_desde_anterior_km', models.DecimalField(decimal_places=2, default=0, help_text='Distancia desde la parada anterior en km', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('es_depot', models.BooleanField(default=False, help_text='Indica si esta parada es el depot (inicio/fin)')),
                ('completada', models.BooleanField(default=False, help_text='Indica si esta parada ha sido visitada')),
                ('hora_llegada_real', models.DateTimeField(blank=True, help_text='Hora real de llegada (cuando se ejecuta la ruta)', null=True)),
                ('hora_salida_real', models.DateTimeField(blank=True, help_text='Hora real de salida (cuando se ejecuta la ruta)', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre esta parada', null=True)),
                ('entrega', models.ForeignKey(blank=True, help_text='Entrega asociada a esta parada (null si es depot)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paradas_asignadas', to='rutas_optimizadas.entrega')),
                ('ubicacion', models.ForeignKey(help_text='Ubicación de esta parada', on_delete=django.db.models.deletion.PROTECT, related_name='paradas', to='ubicaciones.ubicacion')),
                ('ruta', models.ForeignKey(help_text='Ruta a la que pertenece esta parada', on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='rutas_optimizadas.rutaoptimizada')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'db_table': 'paradas',
                'ordering': ['ruta', 'orden'],
                'indexes': [models.Index(fields=['ruta', 'orden'], name='paradas_ruta_id_115178_idx'), models.Index(fields=['ubicacion'], name='paradas_ubicaci_916956_idx')],
                'unique_together': {('ruta', 'orden')},
            },
        ),
        migrations.AddIndex(
            model_name='solicitudruta',
            index=models.Index(fields=['fecha_viaje'], name='solicitudes_fecha_v_ae7b03_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudruta',
            index=models.Index(fields=['estado'], name='solicitudes_estado_4fc49e_idx'),
        ),
        migrations.AddIndex(
            model_name='rutaoptimizada',
            index=models.Index(fields=['solicitud', 'vehiculo'], name='rutas_optim_solicit_af2e72_idx'),
        ),
        migrations.AddIndex(
            model_name='rutaoptimizada',
            index=models.Index(fields=['completada'], name='rutas_optim_complet_fff025_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rutaoptimizada',
            unique_together={('solicitud', 'numero_ruta')},
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['solicitud', 'tipo'], name='entregas_solicit_e242ba_idx'),
        ),
    ]
