# Generated by Django 5.0.7 on 2025-10-20 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_optimizadas', '0001_initial'),
        ('viajes', '0005_cleanup_old_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudruta',
            name='viaje_origen',
            field=models.ForeignKey(blank=True, help_text='Viaje comercial original que generó esta solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_ruta', to='viajes.viaje'),
        ),
    ]
