# Generated by Django 5.0.7 on 2025-11-05 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_optimizadas', '0002_add_depot_salida_regreso'),
        ('rutas_optimizadas', '0002_solicitudruta_viaje_origen'),
    ]

    operations = [
    ]
