# Generated by Django 5.0.7 on 2025-09-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('capacidad_pasajeros', models.IntegerField()),
                ('capacidad_carga', models.DecimalField(decimal_places=1, max_digits=5)),
                ('vin', models.CharField(max_length=50, unique=True)),
                ('seguro_vigente', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En mantenimiento', 'En mantenimiento'), ('Fuera de servicio', 'Fuera de servicio')], default='Disponible', max_length=20)),
            ],
        ),
    ]
