export type User = {
  id: number;
  username: string;
  email: string;
  first_name: string;
  last_name: string;
  telefono?: string;
  direccion?: string;
  ci?: string;
  fecha_nacimiento?: string;
  rol?: {
    id: number;
    nombre: string;
    es_administrativo: boolean;
    permisos: string[];
  };
  is_admin_portal: boolean;
  puede_acceder_admin: boolean;
  personal?: number;
  conductor?: number;
  es_activo: boolean;
  fecha_creacion: string;
  fecha_ultimo_acceso?: string;
  codigo_empleado?: string;
  departamento?: string;
};

export type Personal = {
  id: number;
  nombre: string;
  apellido: string;
  fecha_nacimiento: string;
  telefono: string;
  email: string;
  ci: string;
  codigo_empleado?: string;
  departamento?: string;
  fecha_ingreso?: string;
  horario_trabajo?: string;
  estado?: string;
  supervisor?: number;
  supervisor_nombre?: string;
  supervisor_codigo?: string;
  telefono_emergencia?: string;
  contacto_emergencia?: string;
  es_activo: boolean;
  nombre_completo: string;
  anos_antiguedad: number;
  puede_acceder_sistema: boolean;
  ultimo_acceso?: string;
  fecha_creacion: string;
  fecha_actualizacion: string;
  usuario?: number;
  username?: string;
};

export type Conductor = {
  id: number;
  personal?: number;
  usuario?: number;
  username?: string;
  nombre: string;
  apellido: string;
  email: string;
  telefono: string;
  ci: string;
  fecha_nacimiento: string;
  nro_licencia: string;
  tipo_licencia: string;
  fecha_venc_licencia: string;
  estado: string;
  experiencia_anios: number;
  telefono_emergencia?: string;
  contacto_emergencia?: string;
  es_activo: boolean;
  nombre_completo: string;
  licencia_vencida: boolean;
  dias_para_vencer_licencia: number;
  puede_conducir: boolean;
  ultima_ubicacion_lat?: number;
  ultima_ubicacion_lng?: number;
  ultima_actualizacion_ubicacion?: string;
  fecha_creacion: string;
  fecha_actualizacion: string;
};

export type Role = {
  id: number;
  nombre: string;
  descripcion: string;
  es_administrativo: boolean;
  permisos: string[];
  fecha_creacion: string;
  fecha_actualizacion: string;
};
