# Generated by Django 5.0.7 on 2025-11-02 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReporteGenerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=255, verbose_name="Título del Reporte"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("imagen", "Imagen"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Reporte",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("viajes", "Viajes"),
                            ("encomiendas", "Encomiendas"),
                            ("conductores", "Conductores"),
                            ("vehiculos", "Vehículos"),
                            ("financiero", "Financiero"),
                            ("general", "General"),
                        ],
                        max_length=50,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reportes/%Y/%m/",
                        verbose_name="Archivo Generado",
                    ),
                ),
                (
                    "parametros",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Parámetros utilizados"
                    ),
                ),
                (
                    "fecha_generacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Generación"
                    ),
                ),
                (
                    "tamaño_archivo",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tamaño (bytes)"
                    ),
                ),
                (
                    "tiempo_generacion",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Tiempo de Generación (seg)"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes_generados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte Generado",
                "verbose_name_plural": "Reportes Generados",
                "ordering": ["-fecha_generacion"],
                "indexes": [
                    models.Index(
                        fields=["-fecha_generacion"],
                        name="reportes_re_fecha_g_a891ce_idx",
                    ),
                    models.Index(
                        fields=["categoria", "-fecha_generacion"],
                        name="reportes_re_categor_7fb8ba_idx",
                    ),
                    models.Index(
                        fields=["usuario", "-fecha_generacion"],
                        name="reportes_re_usuario_7945d1_idx",
                    ),
                ],
            },
        ),
    ]
