# Generated by Django 5.2.6 on 2025-11-24 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamosCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Reclamo',
                'verbose_name_plural': 'Categorías de Reclamos',
            },
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('numero_guia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Guía')),
                ('servicio_relacionado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Servicio Relacionado')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='abierto', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='Prioridad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_agente', to=settings.AUTH_USER_MODEL, verbose_name='Agente Asignado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reclamos_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reclamos.reclamoscategoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Reclamo',
                'verbose_name_plural': 'Reclamos',
                'db_table': 'reclamos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ReclamoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('archivo', models.FileField(upload_to='reclamos/adjuntos/%Y/%m/%d/', verbose_name='Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='reclamos.reclamo', verbose_name='Reclamo')),
            ],
            options={
                'verbose_name': 'Adjunto de Reclamo',
                'verbose_name_plural': 'Adjuntos de Reclamos',
                'db_table': 'reclamos_adjuntos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ReclamoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='reclamos.reclamo', verbose_name='Reclamo')),
            ],
            options={
                'verbose_name': 'Detalle de Reclamo',
                'verbose_name_plural': 'Detalles de Reclamos',
                'db_table': 'reclamos_detalle',
                'ordering': ['fecha'],
            },
        ),
    ]
