# Generated by Django 5.0.7 on 2025-10-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ubicacion',
            new_name='ubicaciones_tipo_96ab23_idx',
            old_name='ubicaciones_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='ubicacion',
            new_name='ubicaciones_activo_05f59b_idx',
            old_name='ubicaciones_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='ubicacion',
            new_name='ubicaciones_geohash_f92624_idx',
            old_name='ubicaciones_geohash_idx',
        ),
        migrations.RenameIndex(
            model_name='ubicacion',
            new_name='ubicaciones_lat_bf6cbb_idx',
            old_name='ubicaciones_coords_idx',
        ),
    ]
