# Generated by Django 5.0.7 on 2025-11-06 04:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('frecuencia', models.CharField(choices=[('manual', 'Manual'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='manual', max_length=20)),
                ('hora_ejecucion', models.TimeField(default=django.utils.timezone.now)),
                ('dia_semana', models.IntegerField(blank=True, help_text='0=Lunes, 6=Domingo', null=True)),
                ('dia_mes', models.IntegerField(blank=True, help_text='Día del mes (1-31)', null=True)),
                ('max_backups', models.IntegerField(default=7, help_text='Número máximo de backups a mantener')),
                ('incluir_media', models.BooleanField(default=False, help_text='Incluir archivos media')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('proximo_backup', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_config_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Backup',
                'verbose_name_plural': 'Configuraciones de Backups',
                'db_table': 'backups_config',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('tamanio', models.BigIntegerField(default=0, help_text='Tamaño en bytes')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('tipo', models.CharField(default='database', help_text='database, full, media', max_length=50)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('duracion', models.FloatField(blank=True, help_text='Duración en segundos', null=True)),
                ('mensaje_error', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_creados', to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='backups.backupconfig')),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'db_table': 'backups',
                'ordering': ['-inicio'],
            },
        ),
    ]
