# Generated by Django 5.0.7 on 2025-12-18 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='ID único de la sesión de chat', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de inicio de la conversación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Si la conversación está activa')),
                ('user', models.ForeignKey(help_text='Usuario que inicia la conversación', on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatbot_conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema')], help_text='Rol del emisor del mensaje', max_length=10)),
                ('content', models.TextField(help_text='Contenido del mensaje')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata adicional (intenciones, entidades detectadas, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del mensaje')),
                ('conversation', models.ForeignKey(help_text='Conversación a la que pertenece el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatconversation')),
            ],
            options={
                'db_table': 'chatbot_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('ruta', 'Recomendación de Ruta'), ('viaje', 'Recomendación de Viaje'), ('horario', 'Recomendación de Horario'), ('precio', 'Información de Precio'), ('vehiculo', 'Recomendación de Vehículo'), ('general', 'Recomendación General')], help_text='Tipo de recomendación', max_length=20)),
                ('data', models.JSONField(help_text='Datos de la recomendación (IDs de viajes, rutas, etc.)')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Puntuación de confianza de la recomendación (0-1)')),
                ('was_helpful', models.BooleanField(blank=True, help_text='Feedback del usuario sobre si fue útil', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(help_text='Mensaje que contiene la recomendación', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='chatbot.chatmessage')),
            ],
            options={
                'db_table': 'chatbot_recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user', '-created_at'], name='chatbot_con_user_id_d6d938_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['session_id'], name='chatbot_con_session_975468_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='chatbot_mes_convers_9b53f8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrecommendation',
            index=models.Index(fields=['message', 'recommendation_type'], name='chatbot_rec_message_fa7808_idx'),
        ),
    ]
