# Generated by Django 5.0.7 on 2025-09-12 21:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='modulo',
            field=models.CharField(choices=[('USUARIOS', 'Usuarios'), ('ADMINISTRACION', 'Administracion'), ('TRANSPORTE', 'Transporte'), ('RESERVAS', 'Reservas'), ('PAGOS', 'Pagos'), ('GENERAL', 'General')], default='GENERAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
