# Generated by Django 5.0.7 on 2025-09-14 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
