# Generated by Django 5.0.7 on 2025-09-16 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0002_conductor_email_conductor_first_name_and_more'),
        ('personal', '0004_remove_personalempresa_supervisor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='experiencia_anos',
            new_name='experiencia_anios',
        ),
        migrations.RenameField(
            model_name='conductor',
            old_name='fecha_vencimiento_licencia',
            new_name='fecha_venc_licencia',
        ),
        migrations.RenameField(
            model_name='conductor',
            old_name='numero_licencia',
            new_name='nro_licencia',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='telefono',
        ),
        migrations.AddField(
            model_name='conductor',
            name='personal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductor_profile', to='personal.personal', verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='conductor',
            index=models.Index(fields=['nro_licencia'], name='conductores_nro_lic_cd83a4_idx'),
        ),
        migrations.AddIndex(
            model_name='conductor',
            index=models.Index(fields=['fecha_venc_licencia'], name='conductores_fecha_v_cf0014_idx'),
        ),
    ]
