# Generated by Django 5.0.7 on 2025-09-16 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0003_rename_experiencia_anos_conductor_experiencia_anios_and_more'),
        ('personal', '0005_remove_personal_cargo_remove_personal_salario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='apellido',
            field=models.CharField(default='', max_length=100, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='ci',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='telefono',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='personal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductor_profile', to='personal.personal', verbose_name='Personal'),
        ),
    ]
