# Generated by Django 5.0.7 on 2025-09-14 21:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_personal', models.CharField(choices=[('administrador', 'Administrador'), ('supervisor', 'Supervisor'), ('operador', 'Operador')], max_length=20, verbose_name='Tipo de Personal')),
                ('codigo_empleado', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El código de empleado debe contener solo letras mayúsculas y números', regex='^[A-Z0-9]+$')], verbose_name='Código de Empleado')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario')),
                ('horario_trabajo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horario de Trabajo')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido'), ('vacaciones', 'En Vacaciones')], default='activo', max_length=20, verbose_name='Estado')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Emergencia')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto de Emergencia')),
                ('es_activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='personal.personalempresa', verbose_name='Supervisor')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Personal de Empresa',
                'verbose_name_plural': 'Personal de Empresa',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Presupuesto')),
                ('es_activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('jefe_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_dirigidos', to='personal.personalempresa', verbose_name='Jefe de Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
    ]
