# Generated by Django 5.0.7 on 2025-10-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='usuario',
        ),
    ]
