# Generated by Django 5.0.7 on 2025-09-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_personalempresa_email_personalempresa_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalempresa',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='personalempresa',
            name='tipo_personal',
            field=models.CharField(blank=True, choices=[('administrador', 'Administrador'), ('supervisor', 'Supervisor'), ('operador', 'Operador')], max_length=20, verbose_name='Tipo de Personal'),
        ),
    ]
