# Generated by Django 5.0.7 on 2025-09-16 04:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_personalempresa_departamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalempresa',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='personalempresa',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('tipo_personal', models.CharField(blank=True, choices=[('administrador', 'Administrador'), ('supervisor', 'Supervisor'), ('operador', 'Operador')], max_length=20, verbose_name='Tipo de Personal')),
                ('codigo_empleado', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El código de empleado debe contener solo letras mayúsculas y números', regex='^[A-Z0-9]+$')], verbose_name='Código de Empleado')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario')),
                ('horario_trabajo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horario de Trabajo')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido'), ('vacaciones', 'En Vacaciones')], default='activo', max_length=20, verbose_name='Estado')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Emergencia')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto de Emergencia')),
                ('es_activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='personal.personal', verbose_name='Supervisor')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterField(
            model_name='departamento',
            name='jefe_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_dirigidos', to='personal.personal', verbose_name='Jefe de Departamento'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['ci'], name='personal_pe_ci_e50515_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['email'], name='personal_pe_email_04dc33_idx'),
        ),
        migrations.DeleteModel(
            name='PersonalEmpresa',
        ),
    ]
