# Generated by Django 5.0.7 on 2025-09-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_remove_personalempresa_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='salario',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='tipo_personal',
        ),
    ]
