# Generated by Django 5.0.7 on 2025-10-23 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='modulo',
            field=models.CharField(default='GENERAL', help_text='Módulo del sistema que originó la notificación', max_length=50),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tiponotificacion',
            name='color',
            field=models.CharField(default='#007bff', help_text='Color en formato hexadecimal', max_length=7),
        ),
        migrations.AddField(
            model_name='tiponotificacion',
            name='icono',
            field=models.CharField(default='🔔', help_text='Emoji o icono para la notificación', max_length=10),
        ),
    ]
