# Generated by Django 5.2.6 on 2025-10-09 06:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaEncomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100, unique=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_kg_adicional', models.DecimalField(decimal_places=2, default=5.0, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tarifas_encomienda',
            },
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguimiento', models.CharField(editable=False, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En Ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('remitente_nombre', models.CharField(max_length=200)),
                ('remitente_telefono', models.CharField(max_length=20)),
                ('remitente_direccion', models.TextField(blank=True, null=True)),
                ('destinatario_nombre', models.CharField(max_length=200)),
                ('destinatario_telefono', models.CharField(max_length=20)),
                ('destino_ciudad', models.CharField(max_length=100)),
                ('destino_direccion', models.TextField()),
                ('descripcion', models.TextField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('conductor_asignado', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Conductores'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomiendas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomiendas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'encomiendas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EncomiendaSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='encomiendas.encomienda')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'encomienda_seguimiento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='encomienda',
            index=models.Index(fields=['codigo_seguimiento'], name='encomiendas_codigo__94e4d9_idx'),
        ),
        migrations.AddIndex(
            model_name='encomienda',
            index=models.Index(fields=['estado'], name='encomiendas_estado_644715_idx'),
        ),
        migrations.AddIndex(
            model_name='encomienda',
            index=models.Index(fields=['destino_ciudad'], name='encomiendas_destino_d8df25_idx'),
        ),
        migrations.AddIndex(
            model_name='encomienda',
            index=models.Index(fields=['fecha_creacion'], name='encomiendas_fecha_c_428511_idx'),
        ),
    ]