# Generated by Django 5.2.6 on 2025-10-22 16:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomiendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='encomiendaseguimiento',
            name='encomienda',
        ),
        migrations.RemoveField(
            model_name='encomiendaseguimiento',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='TarifaEncomienda',
        ),
        migrations.AlterModelOptions(
            name='encomienda',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Encomienda', 'verbose_name_plural': 'Encomiendas'},
        ),
        migrations.RenameIndex(
            model_name='encomienda',
            new_name='encomiendas_codigo__03c4bb_idx',
            old_name='encomiendas_codigo__94e4d9_idx',
        ),
        migrations.RenameIndex(
            model_name='encomienda',
            new_name='encomiendas_estado_21fcb7_idx',
            old_name='encomiendas_estado_644715_idx',
        ),
        migrations.RenameIndex(
            model_name='encomienda',
            new_name='encomiendas_destino_aaac46_idx',
            old_name='encomiendas_destino_d8df25_idx',
        ),
        migrations.RenameIndex(
            model_name='encomienda',
            new_name='encomiendas_fecha_c_397e4d_idx',
            old_name='encomiendas_fecha_c_428511_idx',
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='conductor_asignado',
        ),
        migrations.AddField(
            model_name='encomienda',
            name='conductor_asignado_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='pago_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='destinatario_nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='destino_ciudad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='fecha_entrega_estimada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='remitente_nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='encomienda',
            table=None,
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='encomienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='encomiendas.encomienda'),
        ),
        migrations.DeleteModel(
            name='EncomiendaSeguimiento',
        ),
    ]