# Generated by Django 5.2.6 on 2025-10-22 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0003_remove_conductor_usuario'),
        ('encomiendas', '0002_seguimiento_remove_encomiendaseguimiento_encomienda_and_more'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='encomienda',
            name='encomiendas_codigo__03c4bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='encomienda',
            name='encomiendas_estado_21fcb7_idx',
        ),
        migrations.RemoveIndex(
            model_name='encomienda',
            name='encomiendas_destino_aaac46_idx',
        ),
        migrations.RemoveIndex(
            model_name='encomienda',
            name='encomiendas_fecha_c_397e4d_idx',
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='conductor_asignado_id',
        ),
        migrations.AddField(
            model_name='encomienda',
            name='conductor_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomiendas', to='conductores.conductor'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomiendas', to='pagos.pago'),
        ),
    ]
