# Generated by Django 5.0.7 on 2025-10-06 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('Santa Cruz', 'Santa Cruz'), ('Cochabamba', 'Cochabamba'), ('La Paz', 'La Paz')], max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='vehiculos.vehiculo')),
            ],
        ),
    ]
