# Generated by Django 5.0.7 on 2025-10-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='asientos_disponibles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viaje',
            name='asientos_ocupados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='origen',
            field=models.CharField(choices=[('Santa Cruz', 'Santa Cruz'), ('Cochabamba', 'Cochabamba'), ('La Paz', 'La Paz'), ('Oruro', 'Oruro'), ('Potosi', 'Potosi'), ('Tarija', 'Tarija'), ('Beni', 'Beni'), ('Pando', 'Pando')], max_length=50),
        ),
    ]
