# Generated by Django 5.0.7 on 2025-10-12 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0002_rename_ubicaciones_tipo_idx_ubicaciones_tipo_96ab23_idx_and_more'),
        ('vehiculos', '0002_alter_vehiculo_conductor'),
        ('viajes', '0002_viaje_asientos_disponibles_viaje_asientos_ocupados_and_more'),
    ]

    operations = [
        # Paso 1: Renombrar campos existentes a _old
        migrations.RenameField(
            model_name='viaje',
            old_name='origen',
            new_name='origen_old',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='destino',
            new_name='destino_old',
        ),
        
        # Paso 2: Crear campos temporales de texto
        migrations.AddField(
            model_name='viaje',
            name='origen_texto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='destino_texto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        
        # Paso 3: Crear nuevos campos ForeignKey como nullable
        migrations.AddField(
            model_name='viaje',
            name='origen',
            field=models.ForeignKey(
                blank=True, 
                help_text='Ubicación de origen del viaje', 
                null=True, 
                on_delete=django.db.models.deletion.PROTECT, 
                related_name='viajes_origen', 
                to='ubicaciones.ubicacion'
            ),
        ),
        migrations.AddField(
            model_name='viaje',
            name='destino',
            field=models.ForeignKey(
                blank=True, 
                help_text='Ubicación de destino del viaje', 
                null=True, 
                on_delete=django.db.models.deletion.PROTECT, 
                related_name='viajes_destino', 
                to='ubicaciones.ubicacion'
            ),
        ),
        
        # Actualizar otros campos
        migrations.AlterModelOptions(
            name='viaje',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'Viaje', 'verbose_name_plural': 'Viajes'},
        ),
        migrations.AlterField(
            model_name='viaje',
            name='asientos_disponibles',
            field=models.PositiveIntegerField(default=0, help_text='Asientos disponibles para reservar'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='asientos_ocupados',
            field=models.PositiveIntegerField(default=0, help_text='Asientos ya reservados'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', help_text='Estado actual del viaje', max_length=20),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha',
            field=models.DateField(help_text='Fecha del viaje'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='hora',
            field=models.TimeField(help_text='Hora de salida'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio del viaje', max_digits=10),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='vehiculo',
            field=models.ForeignKey(help_text='Vehículo asignado al viaje', on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='vehiculos.vehiculo'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['fecha', 'hora'], name='viajes_viaj_fecha_886adc_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['estado'], name='viajes_viaj_estado_5f77d4_idx'),
        ),
    ]
