# Generated by Django 5.0.7 on 2025-10-12 18:22

from django.db import migrations


def migrate_viajes_to_ubicaciones(apps, schema_editor):
    """
    Migrar viajes existentes para usar ubicaciones en lugar de texto.
    
    Estrategia:
    1. Copiar datos viejos a campos temporales
    2. Buscar o crear ubicaciones correspondientes
    3. Asignar ubicaciones a los viajes
    """
    Viaje = apps.get_model('viajes', 'Viaje')
    Ubicacion = apps.get_model('ubicaciones', 'Ubicacion')
    
    print("📦 Iniciando migración de viajes a ubicaciones...")
    
    # Obtener todos los viajes
    viajes = Viaje.objects.all()
    total_viajes = viajes.count()
    
    if total_viajes == 0:
        print("✅ No hay viajes para migrar")
        return
    
    print(f"📊 Total de viajes a migrar: {total_viajes}")
    
    # Copiar datos viejos a campos temporales y buscar/crear ubicaciones
    viajes_migrados = 0
    ubicaciones_creadas = 0
    
    for viaje in viajes:
        # Guardar textos originales
        viaje.origen_texto = viaje.origen_old
        viaje.destino_texto = viaje.destino_old
        
        # Buscar o crear ubicación de origen
        origen_ubicacion, created = Ubicacion.objects.get_or_create(
            nombre=viaje.origen_old,
            defaults={
                'tipo': 'TERMINAL',  # Por defecto, asumir que son terminales
                'lat': -17.7849,  # Coordenadas por defecto (Santa Cruz)
                'lng': -63.1806,
                'activo': True,
                'source': 'MANUAL'
            }
        )
        if created:
            ubicaciones_creadas += 1
            print(f"  ✨ Ubicación de origen creada: {origen_ubicacion.nombre}")
        
        # Buscar o crear ubicación de destino
        destino_ubicacion, created = Ubicacion.objects.get_or_create(
            nombre=viaje.destino_old,
            defaults={
                'tipo': 'TERMINAL',
                'lat': -17.7849,  # Coordenadas por defecto
                'lng': -63.1806,
                'activo': True,
                'source': 'MANUAL'
            }
        )
        if created:
            ubicaciones_creadas += 1
            print(f"  ✨ Ubicación de destino creada: {destino_ubicacion.nombre}")
        
        # Asignar ubicaciones al viaje
        viaje.origen = origen_ubicacion
        viaje.destino = destino_ubicacion
        viaje.save(update_fields=['origen_texto', 'destino_texto', 'origen', 'destino'])
        
        viajes_migrados += 1
        if viajes_migrados % 10 == 0:
            print(f"  ⏳ Migrados {viajes_migrados}/{total_viajes} viajes...")
    
    print(f"✅ Migración completada:")
    print(f"   - Viajes migrados: {viajes_migrados}")
    print(f"   - Ubicaciones creadas: {ubicaciones_creadas}")


def reverse_migration(apps, schema_editor):
    """
    Revertir la migración copiando los textos de vuelta.
    """
    Viaje = apps.get_model('viajes', 'Viaje')
    
    print("🔄 Revirtiendo migración...")
    
    for viaje in Viaje.objects.all():
        if viaje.origen_texto:
            viaje.origen_old = viaje.origen_texto
        if viaje.destino_texto:
            viaje.destino_old = viaje.destino_texto
        viaje.origen = None
        viaje.destino = None
        viaje.save()
    
    print("✅ Reversión completada")


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_add_ubicacion_fields'),
        ('ubicaciones', '0001_initial'),  # Asegurarse que ubicaciones exista
    ]

    operations = [
        migrations.RunPython(migrate_viajes_to_ubicaciones, reverse_migration),
    ]
