# Generated by Django 5.0.7 on 2025-10-08 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_asiento_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='asiento',
        ),
        migrations.AddField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('pagada', 'Pagada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ItemReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='viajes.asiento')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='viajes.reserva')),
            ],
            options={
                'unique_together': {('asiento',)},
            },
        ),
    ]
