# Generated by Django 5.0.7 on 2025-10-11 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_remove_reserva_asiento_reserva_codigo_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='reserva_temporal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_temporales', to='viajes.reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='viajes.viaje'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado Temporalmente')], default='libre', max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de Pago'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada'), ('pagada', 'Pagada')], default='pendiente_pago', max_length=20),
        ),
    ]
