# Generated by Django 5.0.7 on 2025-10-23 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0002_rename_ubicaciones_tipo_idx_ubicaciones_tipo_96ab23_idx_and_more'),
        ('viajes', '0004_migrate_viajes_to_ubicaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Remover campos antiguos
        migrations.RemoveField(
            model_name='viaje',
            name='origen_old',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='destino_old',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='origen_texto',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='destino_texto',
        ),
        
        # 2. Hacer campos origen y destino obligatorios
        migrations.AlterField(
            model_name='viaje',
            name='origen',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='viajes_origen',
                to='ubicaciones.ubicacion'
            ),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='destino',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='viajes_destino',
                to='ubicaciones.ubicacion'
            ),
        ),
        
        # 3. Crear modelo Reserva
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('estado', models.CharField(
                    choices=[
                        ('temporal', 'Temporal'),
                        ('confirmada', 'Confirmada'),
                        ('cancelada', 'Cancelada'),
                        ('expirada', 'Expirada')
                    ],
                    default='temporal',
                    max_length=20
                )),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('codigo_reserva', models.CharField(max_length=50, unique=True)),
                ('pagado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reservas',
                    to=settings.AUTH_USER_MODEL
                )),
                ('viaje', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reservas',
                    to='viajes.viaje'
                )),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_reserva'],
            },
        ),
        
        # 4. Crear modelo Asiento
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('estado', models.CharField(
                    choices=[
                        ('libre', 'Libre'),
                        ('reservado', 'Reservado'),
                        ('ocupado', 'Ocupado')
                    ],
                    default='libre',
                    max_length=20
                )),
                ('viaje', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='asientos',
                    to='viajes.viaje'
                )),
                ('reserva_temporal', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='asientos_temporales',
                    to='viajes.reserva'
                )),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'ordering': ['viaje', 'numero'],
                'unique_together': {('viaje', 'numero')},
            },
        ),
        
        # 5. Crear modelo ItemReserva
        migrations.CreateModel(
            name='ItemReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asiento', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='item_reserva',
                    to='viajes.asiento'
                )),
                ('reserva', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='items',
                    to='viajes.reserva'
                )),
            ],
            options={
                'verbose_name': 'Item de Reserva',
                'verbose_name_plural': 'Items de Reserva',
            },
        ),
    ]
