# Generated by Django 5.0.7 on 2025-10-12 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0002_rename_ubicaciones_tipo_idx_ubicaciones_tipo_96ab23_idx_and_more'),
        ('viajes', '0004_migrate_viajes_to_ubicaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='destino_old',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='destino_texto',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='origen_old',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='origen_texto',
        ),
        migrations.AlterField(
            model_name='viaje',
            name='destino',
            field=models.ForeignKey(help_text='Ubicación de destino del viaje', on_delete=django.db.models.deletion.PROTECT, related_name='viajes_destino', to='ubicaciones.ubicacion'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='origen',
            field=models.ForeignKey(help_text='Ubicación de origen del viaje', on_delete=django.db.models.deletion.PROTECT, related_name='viajes_origen', to='ubicaciones.ubicacion'),
        ),
    ]
