# Generated by Django 5.0.7 on 2025-10-23 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0002_rename_ubicaciones_tipo_idx_ubicaciones_tipo_96ab23_idx_and_more'),
        ('viajes', '0005_cleanup_and_add_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asiento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemreserva',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.AlterField(
            model_name='asiento',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado Temporalmente')], default='libre', max_length=10),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='numero',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='itemreserva',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='viajes.asiento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de Pago'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada'), ('pagada', 'Pagada')], default='pendiente_pago', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='destino',
            field=models.ForeignKey(help_text='Ubicación de destino del viaje', on_delete=django.db.models.deletion.PROTECT, related_name='viajes_destino', to='ubicaciones.ubicacion'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='origen',
            field=models.ForeignKey(help_text='Ubicación de origen del viaje', on_delete=django.db.models.deletion.PROTECT, related_name='viajes_origen', to='ubicaciones.ubicacion'),
        ),
        migrations.AlterUniqueTogether(
            name='itemreserva',
            unique_together={('asiento',)},
        ),
    ]
