# Generated by Django 5.0.7 on 2025-10-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fecha_ultimo_acceso',
        ),
    ]
