# Generated by Django 5.0.7 on 2025-09-16 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0003_rename_experiencia_anos_conductor_experiencia_anios_and_more'),
        ('personal', '0004_remove_personalempresa_supervisor_and_more'),
        ('users', '0003_rol_fecha_actualizacion_rol_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ci',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='conductor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_conductor', to='conductores.conductor'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin_portal',
            field=models.BooleanField(default=False, verbose_name='Acceso al Panel Administrativo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='personal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_personal', to='personal.personal'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
