# Generated by Django 5.0.7 on 2025-10-06 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conductores', '0003_remove_conductor_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('año_fabricacion', models.IntegerField(blank=True, null=True)),
                ('capacidad_pasajeros', models.IntegerField(default=0)),
                ('capacidad_carga', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En Mantenimiento'), ('baja', 'Dado de Baja')], default='activo', max_length=20)),
                ('kilometraje', models.IntegerField(default=0)),
                ('ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores', to='conductores.conductor')),
            ],
        ),
    ]
