# Generated by Django 5.0.7 on 2025-10-10 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
        ('viajes', '0004_remove_reserva_asiento_reserva_codigo_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='viajes.reserva', verbose_name='Reserva'),
        ),
    ]
